## server
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: SESSION

## spring
spring:
  application:
    name: simple-cms-api
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  h2:
    console:
      enabled: on
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      platform: h2
    timeout: 1800 # 세션 만료 시간 (단위: 초, 30분)

  sql:
    init:
      mode: always
      schema-locations: classpath:db/sql/h2-schema.sql
      data-locations: classpath:db/sql/h2-data.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  threads:
    virtual:
      enabled: on

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

## p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: on

## logging
logging:
  charset:
    console: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  level:
    root: info
    web: info
    com.malgn: debug

## 관리자 가입 코드 - 실제 운영 시에는 환경 변수나 aws secret manager를 사용해주세요
malgn:
  admin:
    secret: "MALGN_ADMIN_SECRET"

